# Generated by Django 5.1.6 on 2025-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verificated_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
