# Generated by Django 5.1.6 on 2025-02-08 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('4164f166-9add-48d9-a6c5-3800748ac503'), unique=True),
        ),
    ]
