# Generated by Django 4.2.1 on 2025-01-27 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Exhibition_image')),
                ('name', models.CharField(max_length=125, verbose_name='введите название выставки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание фотографии')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='Exhibition_image')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='описание фотографии')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='Exhibition_image')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='описание фотографии')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='Exhibition_image')),
                ('description_3', models.TextField(blank=True, null=True, verbose_name='описание фотографии')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='Exhibition_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.articlecategory')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
    ]
